# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:9ZzHW3Uo7XgcbcoEIelHUhb6aNpnbw5joTpzBeo7+wcHilJ35wngkadEDjpER+2fbRiFNlCjqDwEAZbcn+8groJ/7Iu2fMNb2j6fyBHCHf5wi/V9BIjl2AzPcQm5Z5FR5gcX7ID6xD5kNolJ5uEvg0+A2oCF9seh2Q==,iv:qaG6RNXSUFK4BGSJJf2blrjBNDEbPMqUHsvTxEmLiKc=,tag:zqoGQ8fpoUKxxi5Q7SbuFg==,type:str]
sops:
    age:
        - recipient: age1gdt6s73quvrlprl4mt9fssrp378rmxtjrmykwnmvtsrt8g20rd2qh8s5jn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UUprdm8zMnNiV3Y1dlV5
            K091SmNsbTJ5NXNvRDcyeGw4U1ViVXJ6NHlvCkd2aHRVR0h2cUJEK1ZuUXJ3alda
            clVFTUcvVVpiaHh2VnRCZ2JXT2VFT3cKLS0tIHZQcGE5bzN4cjVVTDA4eUw4NERP
            UVFFc1VyUW1RT0FqNXRjUHZmeTgzU2sKjMH+o9InPZ2pAJUcDJMeQ+sZoDvGDUV7
            3uXEB+4P7Fl/srxKq084+5ZlUNTez6h4H1aehw6TIKamQYi0BKLgow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-23T21:57:47Z"
    mac: ENC[AES256_GCM,data:dgbGwmfyVKXkBBcZz8XLK8yQ3VUcTta9UoRAZeQQOGWPxIqmOJzdOi1mTKuR/ev6UeP0xquzisxBf3Tg/aKXWEmMXqs8LRlABi41omgzkw7Fv8/7+qjd/XoOGjwbNYub77z9CpWuzmSHP/Uc7ozSx67KSTEcEYSN6IP8Pe7hNyE=,iv:bTynC/OKk1LvyiZKt5FT3KF8dylYv64UTODbb2bTOPc=,tag:U6o3jOaJAx3u6Jl7vreM2w==,type:str]
    encrypted_regex: ^(address)$
    version: 3.12.1
