apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
type: Opaque
stringData:
  PUSHOVER_TOKEN: ENC[AES256_GCM,data:vailSYAKhKjGjlXNhWCrCqDPIDttDBAi4A0a5OhO,iv:sKfpDzBVQEB9ctJNUC0jmFWkLrG9S2lyMCK3EZn0vx8=,tag:pcfRCs2FOQwKHfy8ELNxQQ==,type:str]
  PUSHOVER_USER_KEY: ENC[AES256_GCM,data:IBAXBnNViz6QSdQIBuHW+DoNxkFO/sbSyoxe1yfs,iv:uj/yixGrS9f98WOiG2CRgKRRY2B1CnLPYF+wUnr4CP0=,tag:gzlPKJbyFf0sH7LjHwP9hA==,type:str]
sops:
  age:
    - recipient: age1gdt6s73quvrlprl4mt9fssrp378rmxtjrmykwnmvtsrt8g20rd2qh8s5jn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0S2hPZWg2S1l2eVhzUEFq
        Y1lieWFoRjBESEJhN29RU1A1Q2ZRRVNyVVhNCmJjS0JNZll3ZVovL2luMHh5Y3I0
        bE93Nzg4UnY1OU5RakZjL2pKRGh5WFEKLS0tIDRnY2RmL0Z1eU1oS3BkQmZpTUwx
        TjZEWUpibWRyRlY1M05EZGxnQ1E2VFUKsBmQonAmmduSCqPTuVCwI1Qsym2/YGu9
        EBuF6DRsOZ9eRC/ecAFY+8luyXKCrEn3uncNPIiTK0MzpOMHA3kkXA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-04T12:51:39Z"
  mac: ENC[AES256_GCM,data:dYneME5TXbIU6PEoIWqdsOGq0LIJd+oird83GsuoyvalsQS5B8i22pq/mYAfc23sk7y8pveomxTw3dVZrWJNdXRUYlIVt1NudGlA3rX28FqOsSjQAMtZk4kI8PIJaNM7FHddtGzssNgCEWtiF5qx2FyhR7mREEe21mrN1wPQuiY=,iv:WKOer2OBNxOvDot1eWsVv0NtGqLYO4abaS8s9bdEvMs=,tag:vDNcN/3RY3RM5AQ5uv0qJg==,type:str]
  encrypted_regex: ^(PUSHOVER_TOKEN|PUSHOVER_USER_KEY)$
  version: 3.12.1
