# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
  name: forgejo-signing-key
  namespace: default
type: Opaque
stringData:
  ed25519: ENC[AES256_GCM,data:Mq5Fltp9JLjp11deqimvHb0md1jfut2kOU5dkoicCf65Lq9C6tQXTdKpwaaIySMP8rGDKVgWJowqxK5Hp0N7KNLNzWg7PhCFOXOpgcyHBUQ6wdbmrF/4PqicPGq9Fq5shE96EXUTSss6sJl6WF7GJvQPf1cDgIMh/izFjg0J+U4AIuy3JR9m5wrduYhEDLBtoNjgD9EV58JMESCy36azhtV3ZTq6nP8ZmAeoivzGboxEmAW5S4zAq76n8/mBLwcAj1sLp/uW8bfV6IiDw6uMtNOf7Ebbfkn68wHcna58PUmClMhg5SaR6RjevdyzqxNmoG4vz/Br5iShlIqbZ4c7vDUkmh/vYGs3cKEoAincryNgHiQQiooOUxp0jL/YLJboyKNn3ZyTFvgsxxK+p3GNIKhUlTrJRFnpdY1nPW+SIU6Sc++ZcHiRYgj2OTJh/bBYbSDZ+97J+oXvdjE6e8lulBmx8DEdIAkPUUwBlsyFHUwT5jogL+pPacu31JWh6rcbddtFehDyZcvHqEPy7qhMTyOQbDkYver9NmtbDgZN9gdVWdhP1EblVkb9fNXjVZpsbgoqa4jZeRJ8RY5ZNHeHSj7FeFg=,iv:KmKD3Jxmsgqw7qIayEL+cAqmXJh4Nayypv5uiL28wlk=,tag:/gKB4YiDkG8fAfpEOtbj0Q==,type:str]
  ed25519.pub: ENC[AES256_GCM,data:xf5jVGCTxZbFiH3AY4CKA7vRndqmoFDT55U/iAlbgdConVOmWu5VD2JQDTr/XWwrEimhCmqv6eN95jc2bs0UknRMZtIgZV2ZcnPnTgM9fAfCGJl5/uaToes+dHK/9YZdepFLt2O9ZpCmmR8FLFdgsj30irkXFOMfzl8K8RWQE56O,iv:syX/pXkEEsl3Pg4BRmpocok5ZuNJb/Z/AA9HTiGGxbk=,tag:Ks7Cp2Xm4894uw/Vb1Q5IQ==,type:str]
sops:
  age:
    - recipient: age1gdt6s73quvrlprl4mt9fssrp378rmxtjrmykwnmvtsrt8g20rd2qh8s5jn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTSk5yZWU4K1MzcGhDanFn
        c0RlVWFkM1VHNEN4c3lDTXNTS3hlMlQzUW40Ck5sVVU2emJ5M3ArbFI0N1B1QWpa
        TG1Gc2JMcWFqcG5nNXExb2ZNVG9yZ1kKLS0tIDNBS0JmTk9qSHRBTndEalpSQ0pl
        V2gwV0l4dTlZSzgyV1AzdE1oZ2xza2cKIREVuBxcoLKJMC4Qw06sb2F6LEEP4v0g
        DzUXN48dTrb0ubgTBs3V9SU76DqLbtWlo5IDrNE9soFqnwIHHS1FLQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-08T00:53:11Z"
  mac: ENC[AES256_GCM,data:YYpV13qY7Hu9SFh0UNoChUCYbmg7cu5/3RcsxXaUkLWvcwTXJ/3MT+Bhl3RekLBDgXznpoQxRaxtYzhZ0UJamDnkppLXJQnZUp8fzprQ5T0jhfG9NYPvJ0T/TMPZs9KQjqX1lEO5dpO8Vwq/F1lo9p8qiWc2ZChTlzy+UsWEa2Q=,iv:4pFPsMqwoPuMIKCun7U475N5aXnz0snBKoQjFYM/o3A=,tag:u378IQwna+CN909AF5ZJlA==,type:str]
  encrypted_regex: ^ed25519
  version: 3.12.1
