apiVersion: v1
kind: Secret
metadata:
  name: forgejo-admin-secret
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:tHZp6KozXHGUL48FZEIz,iv:A81hYFYED9PWdeueaj+PndHbYmf/cttEetMRpfOcszg=,tag:RdybrLcAam9cyryzD6y3Rw==,type:str]
  password: ENC[AES256_GCM,data:OEhr5cYF1kzO4q7oI8zNi1xLwyfl6zMiU2osTYvb16DXMg==,iv:EpK4p7X/l3Afkr7dRXglPGlkdPDDonJLclI+0sqEKNk=,tag:K/z8LZYnjppnTPt+zGa4fA==,type:str]
sops:
  age:
    - recipient: age1gdt6s73quvrlprl4mt9fssrp378rmxtjrmykwnmvtsrt8g20rd2qh8s5jn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQaWk4ZVMvOEVZQlpsbk5p
        RFV2Y1Rya09rYmV2dmxWSGU0a3g2MStjaTMwCnc3Mlp2K1gwSzd6UTM5ZWF3aDVE
        SXhwSklwSGxaWUQwL1ZqV2wrZHlVMjQKLS0tIGtLcjNhaGJGWjFhcXEzY1gxOGRj
        MDVsb09FdXRPblJHZVFzdC9ySVBKeFUKU41A7rfF4+bz1KMZBOG/ZIwWWlOUSahA
        Su65sJ/UQiTuahnOcQpdAGhyfHgBR94Ei3ejNIAPIrAvwTvX7C2ZYQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-08T00:53:51Z"
  mac: ENC[AES256_GCM,data:jn0OM3KOQuL+lsHssuvYUtUrksqb3zcNLksN7bu+EslZqobu19yKBaH98Q5wpbBQAZ+Qc2vGUZVYyOSK2Y+mL4fW//rfbDYNEvMKVUeOM7c8vLVd2RBohCXmi1vf2rSV3IPJ2dRJAp9vFxue9FcBRfOFZ+sv0BR5G8+2HcVkqEw=,iv:wnwRPxig5bhbrtvzOfTcJVWpyPPKeDwd9XQIpuvLz/M=,tag:fQFPY2hi8WnLkwOzagKA9w==,type:str]
  encrypted_regex: ^(username|password)$
  version: 3.12.1
