---
creation_rules:
  - path_regex: talos-secrets.yaml
    encrypted_regex: "^(secret|secretboxencryptionsecret|crt|key)$"
    key_groups:
      - age:
          - age1gdt6s73quvrlprl4mt9fssrp378rmxtjrmykwnmvtsrt8g20rd2qh8s5jn

stores:
  yaml:
    indent: 2
