# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: kube-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
type: Opaque
stringData:
    age.agekey: ENC[AES256_GCM,data:E2zBxwVW29BMV56qxgOr5sNar7+O5jjO+FyDqI8DsbUsy2Vz0/5yU7ndVu3y2Wlh4Cm7XUa40xgnOxsBrRyKZ+hfvlV8CRa/EqJe9EpRTYi+rTubD7i5LkCCxx4Vr7V+1zwBJ1EGqXYZxQuVkArpAZzUJNZnqNczr5OXY0fZU7H2aKW9WvagIbuMpF4YpjZ/IhQ0G5FwKUC74Km7vOBqB4ynXp6QezVYL8rNzjy/5dxFI8x3jPeNdM+lmh+3,iv:X3h0je1bI50UDRS8eX65xxBI8OFPCHDCX90j5ufiCaw=,tag:yK42Pd/E9qf727gRQqledw==,type:str]
sops:
    age:
        - recipient: age1gdt6s73quvrlprl4mt9fssrp378rmxtjrmykwnmvtsrt8g20rd2qh8s5jn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWTk5b0EvcVdUUmhmcm5j
            UC8veW1UaE1BN0Rjb1NZOEgzY0lLSkQ3Qm5RCmFJZUtONVRrOWhtcmZtQ2Z3L3JV
            MkNIYW0zSVFOSm1SNjJkQUZaQnNOemcKLS0tIHRINTd0Yklod2ZuOWJrZzZxbTgr
            aDdneVdWR0MwZ1IrRjU2bWNmdncxSVkKUP7anGlC/3p7CPCM0Mv6n86WE2pi/3JD
            A+JvueGeHp4KmmtEd60PPPKWCV0NZRFDWfOzHVPslm8zY5CL8frYvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-27T22:32:33Z"
    mac: ENC[AES256_GCM,data:OSz8PnNy2ldlSn5WGupr+QC3BnCVx/mgh0hY7t/W07n/heI3JJi2uiZQ6Pz1+BrUCs+Z2tktHpapWZPAHqbwSdSqur/ZyqYBbDiHz4ECWAeH1ycjY6Ipqu8Ip8NUNqoxgBi8AI5vfHpkV4v1LdsNlfuA6RmdlNJrt4kdWg47ozA=,iv:lzBlWDz+SbE/scU/n6Rl71rI0CUkMb1TBaQY/e71bxg=,tag:P5Q0joEeRLIeR0cnBbcAgg==,type:str]
    encrypted_regex: ^(age.agekey|identity)$
    version: 3.12.1
