# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    cloudflare-token: ENC[AES256_GCM,data:Vbw2Hq/gmDuA6+fSku9COs/G+t66WpBXGorRFCVw1UOMUeFBcuYQgNTiyfIogNMqWcpnr2U=,iv:B0K0+Q803hykL/TBv6+EwYP3qjGzdbp+vrXrWL/h3Mc=,tag:GkiE9J+Mx6T6FC/YLK6ryg==,type:str]
sops:
    age:
        - recipient: age1gdt6s73quvrlprl4mt9fssrp378rmxtjrmykwnmvtsrt8g20rd2qh8s5jn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNW11WXB6SHV6a2MzSUNU
            c052cWZnT0xNNTA4d2hKaTNsYkV3SGpZc3lFCk9uRVFaNllGbDRNSVlDUDVUSUhi
            MHJzS0lZT0Qyd1paZVJQTHB2N3VyNGMKLS0tIE5RZnhSRzFldThPYlJhU0NBZG1O
            Tkw0ZWVHMmxRK0dYK0poOFc5clgxc0UKoBfhd4400GNjXvPwXvYmXjxWgVSvAr+J
            1GBg8c2fQND87k7zMV8lqZxAsFqssdwVI69TZE83smDhQ8IoajwB0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-08T00:07:50Z"
    mac: ENC[AES256_GCM,data:Bl1JK6PVlP8jo7FDeTBlNXO9H/P425HCncT6uomQOinEPSAxc1TUx7nG5Z4TLBTZyXovyxX0xMUIDJEMUA/MUYph+O4puvfTq97KCXkPwhRQUk42E2F7ZWPmEJESEE7bMbb/HDoY6/tH6mEn1IclTbcR+V91iLFe5kfwn+ErDAI=,iv:GenCvBZO789mvNGEpffqd8Is+yJ0z8faZ+eVK6erE6Q=,tag:NfPBISAJYxZh4QDhudRh5w==,type:str]
    encrypted_regex: ^(cloudflare-token)$
    version: 3.12.1
