# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/configmap_v1.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-vars
data:
  CLUSTER_DOMAIN: forgejo.infrastructure.untouchedwagons.com # ${CLUSTER_DOMAIN}
  CLUSTER_NAME: Forgejo cluster # ${CLUSTER_NAME}
  GIT_REPO_URL: https://github.com/UntouchedWagons/Forgejo.git # ${GIT_REPO_URL}
  GIT_REPO_BRANCH: main # ${GIT_REPO_BRANCH}
