# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/secret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-volsync-secret
stringData:
    RESTIC_PASSWORD: ENC[AES256_GCM,data:sVHTo9EkbpJKEh3CfHPWpFnAEw9HFWNRjZs=,iv:jGoj/yi0/M/DkuvYM+z+cCA9IQNttg2VRL1V7hYgl40=,tag:OWWYCqwafMmG9wH8GVowjw==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:8QRS0IcoPCQM9ZvLicOsSPBvxEqYdST4oQWXH5DYlHtMyrfT2z8w5ddoRO0yaTg=,iv:7Et+Zi36ezwxeXQrL2N6rz/blKUL/ifFniHE+6+I3mg=,tag:Oc1JH/hNSNl0w8I4mkEYyQ==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1gdt6s73quvrlprl4mt9fssrp378rmxtjrmykwnmvtsrt8g20rd2qh8s5jn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYOUt6K0hoMTdMeG1FMnkv
            bkpkVWYySmxTVW5udldMd2hLTVFQZmppNlFRCmJkMWZ1UWI5VTJnVkhuN1JPNTY3
            dGhNVFh3Q3J2V2dWTUFsQ0IyU2FiWTgKLS0tIGRxaGRvWlFaZnQzZzRjSUNXUFlL
            Mk1FbkRkSlBhNGhBVitGZ3NYUi9Yb28Khz1922FjDMyGl+yv/xZDi055Qir+tB2t
            nzrmY0IJa/9AkT7vxdcyjIQ2eXvGV/2W0uyhKfEMJljRNk+Y8X89Vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-08T00:02:38Z"
    mac: ENC[AES256_GCM,data:nDxC2G7aDKkt+R0Kj22cPt7qwmZZAKh0sn54nJtcxm77TUT9GBeQp+KKmuHlfFEJTChgjwMgLCOSUDtSzTuuaKI1iFdBQ18V7NTjIUgPu/3vcjgLyqJmPvrux6+MCIoo1+oqsYXwGeTLUcCa+Ws75J9LDATq1TKcDIYwqHeu0Ns=,iv:4aJUZTkB6QeVm2dq2BbTF+ZCx9J5Zdy7h0UgBoUGMtg=,tag:kkYRiiwgZ5wZ7RG2xOkuNg==,type:str]
    encrypted_regex: ^(RESTIC_PASSWORD|AWS_ACCESS_KEY_ID|AWS_SECRET_ACCESS_KEY|RESTIC_REPOSITORY)$
    version: 3.13.1
